- name: installing redis component
  hosts: redis
  become: yes
  tasks:
    - name: installing redis repo
      ansible.builtin.command: yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

    - name: enabling redis 
      ansible.builtin.command: yum module enable redis:remi-6.2 -y

    - name : installing redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: replacing ip
      ansible.builtin.replace:  
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'   

    - name: enabling and starting
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: yes    